image: ubuntu/18.04
packages:
- curl
- protobuf-compiler
- libprotoc-dev
- libraptor2-dev
sources:
- https://git.sr.ht/~gabe/hod
tasks:
  - setup-go: |
      curl -O https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
      sudo tar -C /usr/local -xzf go1.11.2.linux-amd64.tar.gz
  - build-hod: |
      export PATH=$PATH:/usr/local/go/bin
      cd hod
      go get
      make build
  - test-hod: |
      export PATH=$PATH:/usr/local/go/bin
      cd hod
      make test
