HodConfig = "2.yml"
ListenPort = 3001

[[Peer]]
Address = "localhost:3000"
[[Peer.Wants]]
    Graphs = ["test"]
    Definition = """SELECT ?s ?p ?o WHERE {
                    ?s rdf:type/rdfs:subClassOf* brick:Point .
                    ?s ?p ?o
                 };"""
[[Peer.Wants]]
    Graphs = ["test"]
    Definition = """SELECT ?room ?floor WHERE {
                    ?room rdf:type brick:Room .
                    ?room bf:isPartOf ?floor .
                    ?floor rdf:type brick:Floor
                 };"""
